sudo: required
dist: trusty
language: python
cache: pip
python:
  - 2.7
  - 3.5
  - 3.6

before_install:
  - pip install -r dev_requirements.txt

notifications:
  email:
    on_success: never
    on_failure: never
